# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:

- job: build
  displayName: Build
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - script: echo built


- job: 'Test'
  displayName: 'Unit tests'
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: build
  steps:
    script |
    cd Simple_Server/src/tests/
    javac TestWinnerBored.java
    java TestWinnerBored.class
    rm TestWinnerBored.class
  
