# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:

- job: build
  displayName: Build
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - script: echo built


- job: 'Test'
  displayName: 'Unit tests'
  pool:
    vmImage: 'Ubuntu-16.04'
  dependsOn: build
  steps:
    - script: |
        apt-get update
        apt-get install java-jdk
        cd Simple_Server/src/tests/
        javac TestWinnerBored.java
        java TestWinnerBored.class


- job: 'Deploy'
  displayName: 'Deploy'
  pool:
    vmImage: ubuntu-16.04
  dependsOn: build
  steps:
    # Download Secure File
    # Download a secure file to a temporary location on the build or release agent
    - task: DownloadSecureFile@1
      inputs:
          secureFile: pong_server_keys.pem
    - script: |
        scp -i "$(Agent.TempDirectory)/pong_server_keys.pem" -r $(Build.SourcesDirectory) ubuntu@ec2-18-219-148-13.us-east-2.compute.amazonaws.com:programs/
        